### ISSUE TITLE
Some my code isn't working

### ISSUE THREAD

**Issue by ElijahGives** [Ximaz/js-deobfuscator#1]
I'm tryna deobfuscate a script that I have, I'll put it below.
It's giving the error.
X:\X\JS-Deobfuscator>py main.py code.js
Traceback (most recent call last):
  File "main.py", line 113, in <module>
    main()
  File "main.py", line 68, in main
    array_name, array, match = find_strings_array(code)
  File "main.py", line 26, in find_strings_array
    array_name = raw_array.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

SCRIPT:
[The code is here](https://github.com/Quatrecentquatre-404/js-desobfuscator/files/7448896/obf.txt)

**Comment by Quatrecentquatre-404** [comment]
May you edit the message to put an attachment rather sending the whole code in the message ? Thanks in advance.

**Comment by ElijahGives** [comment]
alr

**Comment by ElijahGives** [comment]
it doesnt let me upload .js files, ill dm u on discord the file link.

**Comment by Quatrecentquatre-404** [comment]
I just analyzed the code and there is a spec that the desobfuscator cannot handle yet, the OSA shuffling. The OSA is followed by a function that shuffle it and so, references aren't same between what the code see and what the runtime sees. I don't really know how to implement thisone excepted by running the script and try to make a breakpont a the end of this function. For now, you'ill have to handjob it.

**Comment by Ximaz** [comment]
So, actually, I improved the code a lot, and you shouldn't get any error now. Actually, it won't deobfuscate your source since it doesn't matches the OSA scheme, which is the only one I support for now. But there are some features that do not require you to have an OSA schema such as hex numbers going to decimals ones, handling ``![]`` and ``!![]`` as boolean and replace it in code, renaming unused variables and function as ``UNUSED_<an_index>``, but also a renaming to a shorter label : ``a<an_index>``. You can see some examples into the [https://github.com/Ximaz/js-deobfuscator/blob/main/issues/ElijahGives/output.js](issues/) folder I created for code issues. In addition, it also handles the ``- -`` operators and ``-+``, etc... I hope it will help you a little bit more, but for now, you'll have to do the remaining work by hand.

**Comment by valandexx** [comment]
@quatrecent-quatre404
@Ximaz (Is it possible to make it support that kind of obfuscation the code has?)

**Comment by Ximaz** [comment]
Well, actually, I don't know how to make it because each obfuscation is differently from the top to the bottom. The only thing they might have in common are :
- names pattern : ``_0xXXXXX`` (example), I'm able to see if it's used or not, and renaming it to make it easier to read,
- numbers as hexadecimal : I'm able to make it as decimal,
- booleans as ``!![]`` and ``![]``.
- escaped strings (or unicode strings) : I'm able to make them readable.
The only other thing which I'm able to fully handle is OSA, but not all obfuscation has it.

**Comment by Ximaz** [comment]
Actually, I may have found a workaround for dead injection detection and removal. In addition, I added a math lexer to make maths for you.

**Comment by Ximaz** [comment]
Also, I made some research and I figured out their is an OSA on your code, yet it won't apply because the indexes that refers to the OSA are stored into variables, which I don't know for now how to extract number in it. I've chose to let the OSA at the beginning of the code if for some reason it can't be applied.
